### ISSUE TITLE
Comparisons between other systems?

### ISSUE THREAD

**Issue by RedDude** [guerrillacontra/Unity-Message-Hub#2]
Hello!

I really considering replace my message system, and Unity-Message-Hub seems to be the right choice. 
But, do you have any benchmarking with other systems? ie. SendMessage, The new one from UI other any from ones of Unity Wiki

Would be really usefull.

Thanks

**Comment by guerrillacontra** [comment]
Hello @RedDude,

Sorry there are currently no benchmarks however Unity Messenger will be slower as it uses reflection while the Message Hub is almost direct access each time.

Message Hub is much simpler and far lighter.

For me it is not too much about performance but more about the design.

So Message Hub is type-safe (using generic's) while Unity's is not.

This makes it much more obvious to listen/post messages that are of the correct type and process them
while being faster.

**Comment by RedDude** [comment]
@guerrillacontra 

I totally agree with you, the design of Unity-Message-Hub is simple and lighter. 
Thats why I think it will fit some of my needs.
But I am asking because my game it pretty slow on an Ipad, currently I am using "TinyMessage" (https://github.com/grumpydev/TinyMessenger) which is also type-safe but not a "for unity" solution.

Anyway, When I got time, I will benchmark many message systems, Unity-Message-Hub will be one of them for sure.
